# Generated by Django 4.1.7 on 2023-03-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_rename_acitve_users_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='name',
            new_name='searched_item',
        ),
    ]
