from AdminPanel.http_views.tags_view import TagsView
from AdminPanel.http_views.blog_tag_mapping_view import BlogTagMappingView
from AdminPanel.http_views.blogs_view import BlogsView
from AdminPanel.http_views.users_view import UsersView
from AdminPanel.http_views.history_view import HistoryView